# Only supports MySQL at the moment
database:
  type: SQLITE # MYSQL or SQLITE
  host: "localhost" # Only for MySQL
  port: "3306" # Only for MySQL
  database: "database" # Only for MySQL
  username: "username" # Only for MySQL
  password: "password" # Only for MySQL
  options: "useSSL=false" # Only for MySQL
  table-prefix: "pnts_"
  sqlite-file: "points.db" # Only for SQLite

points:
  default: 0.0 # Is a double (decimal) value
  on-join:
    load: true # If true, will load the player's points when they join the server
  on-quit:
    save: true # If true, will save the player's points when they quit the server
    dispose: true # If true, will dispose the player's profile in memory when they quit the server
  save-interval: 5 # In minutes