# Configurations for Spawn.
spawn:
  # Teleport to spawn on join.
  on-join: false
  # Spawn command.
  command:
    # If you want to go to main spawn by default.
    main-by-default: true

# Configurations for flight.
flight:
  # Flight toggling.
  toggle:
    # Put players on the ground when they toggle flight off.
    put-on-ground: true
    # Check if player is able to fly on join.
    check-on-join: true
    # Check if player is able to fly on join.
    check-on-leave: false
    # Check if player is able to fly on move.
    check-on-move: false
  # Check permissions.
  permissions:
  - justessentials.command.fly

# Configurations for heal.
heal:
  # Bad effects to remove.
  bad-effects:
    - BLINDNESS
    - CONFUSION
    - HUNGER
    - POISON
    - SLOW
    - SLOW_DIGGING
    - WEAKNESS
    - WITHER
    - UNLUCK

# Configurations for feed.
feed:
  # Bad effects to remove.
  bad-effects:
    - HUNGER