name: '${name}'
version: '${version}'
main: '${main}'
authors:
  - Drak
depend:
  - BukkitOfUtils
  - PlaceholderAPI
folia-supported: true

commands:
  points:
    description: Main command for JustPoints
    permission: justpoints.command.points
    usage: /<command>
    aliases: [pnts, point, pnt]