name: '${name}'
version: '${version}'
main: '${main}'
authors:
  - Drakify

commands:
  points:
    description: Main command for JustPoints
    permission: justpoints.command.points
    usage: /<command>
    aliases: [pnts, point, pnt]