name: JustPoints
version: '${version}'
main: host.plas.justpoints.JustPoints
author: Drakify

commands:
  points:
    description: Main command for JustPoints
    permission: justpoints.command.points
    usage: /<command>
    aliases: [pnts, point, pnt]